import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { abarMid } from "@/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="fa" dir="rtl" className={`${abarMid.variable} ${geistSans.variable}`}>
      <body>{children}</body>
    </html>
  );
}
